version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: fines
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: fines

	fines:
		build: .
		image: chamaconekt/fines
		links:
		- postgres
		container_name: fines
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- fines
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/fines-nginx/nginx.conf
		depends_on:
			- fines
		ports:
			- 80:80
		volumes_from:
			- fines

volumes:
	fines-static-files:
		driver:local